version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOCKER=true  # Make sure this is set to 'true'
    command: ["npm", "run", "start"]
